export enum BibleBookEnum {
  OT_Genesis = 'ot_genesis',
  OT_Exodus = 'ot_exodus',
  OT_Leviticus = 'ot_leviticus',
  OT_Numbers = 'ot_numbers',
  OT_Deuteronomy = 'ot_deuteronomy',
  OT_Joshua = 'ot_joshua',
  OT_Judges = 'ot_judges',
  OT_Ruth = 'ot_ruth',
  OT_1Samuel = 'ot_1_samuel',
  OT_2Samuel = 'ot_2_samuel',
  OT_1Kings = 'ot_1_kings',
  OT_2Kings = 'ot_2_kings',
  OT_1Chronicles = 'ot_1_chronicles',
  OT_2Chronicles = 'ot_2_chronicles',
  OT_Ezra = 'ot_ezra',
  OT_Nehemiah = 'ot_nehemiah',
  OT_Esther = 'ot_esther',
  OT_Job = 'ot_job',
  OT_Psalms = 'ot_psalms',
  OT_Proverbs = 'ot_proverbs',
  OT_Ecclesiastes = 'ot_ecclesiastes',
  OT_SongOfSolomon = 'ot_song_of_solomon',
  OT_Isaiah = 'ot_isaiah',
  OT_Jeremiah = 'ot_jeremiah',
  OT_Lamentations = 'ot_lamentations',
  OT_Ezekiel = 'ot_ezekiel',
  OT_Daniel = 'ot_daniel',
  OT_Hosea = 'ot_hosea',
  OT_Joel = 'ot_joel',
  OT_Amos = 'ot_amos',
  OT_Obadiah = 'ot_obadiah',
  OT_Jonah = 'ot_jonah',
  OT_Micah = 'ot_micah',
  OT_Nahum = 'ot_nahum',
  OT_Habakkuk = 'ot_habakkuk',
  OT_Zephaniah = 'ot_zephaniah',
  OT_Haggai = 'ot_haggai',
  OT_Zechariah = 'ot_zechariah',
  OT_Malachi = 'ot_malachi',
  NT_Matthew = 'nt_matthew',
  NT_Mark = 'nt_mark',
  NT_Luke = 'nt_luke',
  NT_John = 'nt_john',
  NT_Acts = 'nt_acts',
  NT_Romans = 'nt_romans',
  NT_1Corinthians = 'nt_1_corinthians',
  NT_2Corinthians = 'nt_2_corinthians',
  NT_Galatians = 'nt_galatians',
  NT_Ephesians = 'nt_ephesians',
  NT_Philippians = 'nt_philippians',
  NT_Colossians = 'nt_colossians',
  NT_1Thessalonians = 'nt_1_thessalonians',
  NT_2Thessalonians = 'nt_2_thessalonians',
  NT_1Timothy = 'nt_1_timothy',
  NT_2Timothy = 'nt_2_timothy',
  NT_Titus = 'nt_titus',
  NT_Philemon = 'nt_philemon',
  NT_Hebrews = 'nt_hebrews',
  NT_James = 'nt_james',
  NT_1Peter = 'nt_1_peter',
  NT_2Peter = 'nt_2_peter',
  NT_1John = 'nt_1_john',
  NT_2John = 'nt_2_john',
  NT_3John = 'nt_3_john',
  NT_Jude = 'nt_jude',
  NT_Revelation = 'nt_revelation',
}

/**
 * List of all Bible books in order
 */
export const BIBLE_BOOKS_ORDERED_LIST: readonly BibleBookEnum[] = Object.freeze(
  [
    BibleBookEnum.OT_Genesis,
    BibleBookEnum.OT_Exodus,
    BibleBookEnum.OT_Leviticus,
    BibleBookEnum.OT_Numbers,
    BibleBookEnum.OT_Deuteronomy,
    BibleBookEnum.OT_Joshua,
    BibleBookEnum.OT_Judges,
    BibleBookEnum.OT_Ruth,
    BibleBookEnum.OT_1Samuel,
    BibleBookEnum.OT_2Samuel,
    BibleBookEnum.OT_1Kings,
    BibleBookEnum.OT_2Kings,
    BibleBookEnum.OT_1Chronicles,
    BibleBookEnum.OT_2Chronicles,
    BibleBookEnum.OT_Ezra,
    BibleBookEnum.OT_Nehemiah,
    BibleBookEnum.OT_Esther,
    BibleBookEnum.OT_Job,
    BibleBookEnum.OT_Psalms,
    BibleBookEnum.OT_Proverbs,
    BibleBookEnum.OT_Ecclesiastes,
    BibleBookEnum.OT_SongOfSolomon,
    BibleBookEnum.OT_Isaiah,
    BibleBookEnum.OT_Jeremiah,
    BibleBookEnum.OT_Lamentations,
    BibleBookEnum.OT_Ezekiel,
    BibleBookEnum.OT_Daniel,
    BibleBookEnum.OT_Hosea,
    BibleBookEnum.OT_Joel,
    BibleBookEnum.OT_Amos,
    BibleBookEnum.OT_Obadiah,
    BibleBookEnum.OT_Jonah,
    BibleBookEnum.OT_Micah,
    BibleBookEnum.OT_Nahum,
    BibleBookEnum.OT_Habakkuk,
    BibleBookEnum.OT_Zephaniah,
    BibleBookEnum.OT_Haggai,
    BibleBookEnum.OT_Zechariah,
    BibleBookEnum.OT_Malachi,
    BibleBookEnum.NT_Matthew,
    BibleBookEnum.NT_Mark,
    BibleBookEnum.NT_Luke,
    BibleBookEnum.NT_John,
    BibleBookEnum.NT_Acts,
    BibleBookEnum.NT_Romans,
    BibleBookEnum.NT_1Corinthians,
    BibleBookEnum.NT_2Corinthians,
    BibleBookEnum.NT_Galatians,
    BibleBookEnum.NT_Ephesians,
    BibleBookEnum.NT_Philippians,
    BibleBookEnum.NT_Colossians,
    BibleBookEnum.NT_1Thessalonians,
    BibleBookEnum.NT_2Thessalonians,
    BibleBookEnum.NT_1Timothy,
    BibleBookEnum.NT_2Timothy,
    BibleBookEnum.NT_Titus,
    BibleBookEnum.NT_Philemon,
    BibleBookEnum.NT_Hebrews,
    BibleBookEnum.NT_James,
    BibleBookEnum.NT_1Peter,
    BibleBookEnum.NT_2Peter,
    BibleBookEnum.NT_1John,
    BibleBookEnum.NT_2John,
    BibleBookEnum.NT_3John,
    BibleBookEnum.NT_Jude,
    BibleBookEnum.NT_Revelation,
  ],
);
