name: Deploy Production
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    # https://github.com/conradkoh/biblestudy/settings/environments
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Deploy with Convex
        env:
          # Secrets can be configured at https://github.com/conradkoh/biblestudy/settings/environments/3827949176/edit
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
        run: yarn deploy